[package]
name = "tts-api"
version = "0.0.0"
authors = [ "Walker <yuitanabe@aol.com>" ]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
js-sys = "*"
hyper = { version = "*", features = ["client"]}